InternetFinalProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_reset/', include('django.contrib.auth.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('login/',login_view,name="login"),
    path('logout/',logout_view,name="logout"),
    path('signup/',signup_view,name="signup"),
    path('forgot-password/', forgot_password, name='forgot_password'),

    path('reset-password/<str:token>/', reset_password, name='reset_password'),
    
]

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    #path('url address', 'view', 'name')

    path('',shop_view,name="shop"),
    path('<str:filter>',shop_view,name='shop'),
    path('single/<int:pid>',shop_single,name="single"),
    path('cart/',cart_view,name='cart'),
    path('update_item/', updateItem, name='update_item'),
    path('checkout/',checkout_view,name='checkout'),
    path('search/',search_view,name='search'),
    path('tag/<str:tag_name>',shop_view,name="tag"),
    # path('about',about_view,name="about"),
    # path('test',test,name="test"),
    # path('newsletter',newsletter_view,name="newsletter"),
]

templates/website_templates/cart.html
{% extends "base.html" %}

{% block content %}
{% load static %}


    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/art-materials-colored-pencils.webp' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'website:shop' %}">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table >
                            <thead>
                                <tr>
                                    <th class="shoping__product"></th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for orderitem in orderitems %}
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img src="{{orderitem.item.image.url}}" alt="">
                                        <h5>{{orderitem.item.title}}</h5>
                                    </td>
                                    <td class="shoping__cart__price">
                                        {{orderitem.item.final_price}}
                                    </td>
                                    <td class="shoping__cart__quantity">
                                        <p style="color:black; font-weight: bolder;" onmouseover="this.style.cursor='pointer';" onmouseout="this.style.cursor='default';"
                                        data-item="{{orderitem.item.id}}" data-action="add" class="update-cart">+</p>
                                        
                                            <p style="color:black; font-weight: bolder;" >{{orderitem.quantity}}</p>
                                    
                                        <p style="color:black; font-weight: bolder;"onmouseover="this.style.cursor='pointer';" onmouseout="this.style.cursor='default';"
                                        data-item="{{orderitem.item.id}}" data-action="remove" class="update-cart">-</p>

                                    </td>
                                    <td class="shoping__cart__total">
                                       {{orderitem.get_total}}$
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">

                </div>
                <!-- <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="#">
                                <input type="text" placeholder="Enter your coupon code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div> -->
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Total Items <span>{{order.get_cart_items}}</span></li>
                            <li>Total Price<span>{{order.get_cart_total}}$</span></li>
                        </ul>
                        <a href="{% url 'website:checkout' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->

   {% endblock %}

templates/website_templates/category.html
<div class="hero__categories">
<div class="hero__categories__all">
    <i class="fa fa-bars"></i>
    <span>Categories</span>
</div>
<ul>
    {% for tag in tags %}
    <li><a href="{% url 'website:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
    {% endfor %}
</ul>
</div>

templates/website_templates/checkout.html
{% extends "base.html" %}

{% block content %}
{% load static %}



    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/art-materials-colored-pencils.webp' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'website:shop' %}">Shop</a>
                            <span>Checkout</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">

            <div class="checkout__form">
                <h4>Billing Details</h4>
                <form action="#">
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Fist Name<span>*</span></p>
                                        <input type="text">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" placeholder="Street Address" class="checkout__input__add">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Phone<span>*</span></p>
                                        <input type="text">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="text">
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4>Your Order</h4>
                                <div>
                                    <table style="width:100%;">
                                        <thead>
                                          <tr>
                                            <th>Item</th>
                                            <th>Number</th>
                                            <th>Price</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            {% for orderitem in orderitems %}
                                          <tr>
                                            
                                            <td>{{orderitem.item.title}}</td>
                                            <td>{{orderitem.quantity}}</td>
                                            <td>{{orderitem.get_total}}$</td>
                                           
                                          </tr>
                                          {% endfor %}
                                        </tbody>
                                      </table>
                                      
                                <div class="checkout__order__subtotal">Total Items <span>{{order.get_cart_items}}</span></div>
                                <div class="checkout__order__total">Total Price <span>{{order.get_cart_total}}$</span></div>

                                <button type="" class="site-btn"><a href="{% url 'website:shop' %}">PLACE ORDER</a></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

 {% endblock %}

templates/website_templates/search.html
<div class="hero__search__form">
    <form action="{% url 'website:search' %}">
        <input type="text" placeholder="What do yo u need?" name="s">
        <button type="submit" class="site-btn">SEARCH</button>
    </form>
</div>

templates/website_templates/shop-paginator.html
{% load static %}

<div class="product__pagination">
    {% for i in items.paginator.page_range %}
    {% if i == items.number %}
    <a href="?page={{i}}" style="background-color:chartreuse">{{i}}</a>
    {% else %}
    <a href="?page={{i}}">{{i}}</a>
    {% endif %}

    {% endfor %}
</div>

templates/website_templates/shop-single.html
{% extends "base.html" %}

{% block content %}
{% load static %}


    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/art-materials-colored-pencils.webp' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>{{item.title}}</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'website:shop' %}">Shop</a>
                            <span>{{item.title}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__item">
                            <img class="product__details__pic__item--large"
                                src="{{item.image.url}}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{item.title}}</h3>
                        <div class="product__details__rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <!-- <span>(18 reviews)</span> -->
                        </div>
                        <div class="product__details__price">{{item.final_price}}$</div>
                        <p>{{item.description}}</p>
                        <!-- <div class="product__details__quantity">
                            <div class="quantity">
                                <div class="pro-qty">
                                    <input type="text" value="1">
                                </div>
                            </div>
                        </div> -->
                        <a href="#" class="primary-btn update-cart" data-item="{{item.id}}" data-action="add">ADD TO CARD</a>
                        <ul>
                            {% if item.status %}
                            <li><b>Availability</b> <span>In Stock</span></li>
                            {% else %}
                            <li><b>Availability</b> <span>None</span></li>
                            {% endif %}
                            <li><b>Size</b> <span>{{item.size}}</span></li>
                            <li><b>Color</b> <span>{{item.color}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-12">
                    <!-- <div class="product__details__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
                                    aria-selected="true">Description</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
                                    aria-selected="false">Information</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab"
                                    aria-selected="false">Reviews <span>(1)</span></a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="product__details__tab__desc">
                                    <h6>Products Infomation</h6>
                                    <p>Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
                                        Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus. Vivamus
                                        suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam sit amet quam
                                        vehicula elementum sed sit amet dui. Donec rutrum congue leo eget malesuada.
                                        Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur arcu erat,
                                        accumsan id imperdiet et, porttitor at sem. Praesent sapien massa, convallis a
                                        pellentesque nec, egestas non nisi. Vestibulum ac diam sit amet quam vehicula
                                        elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus
                                        et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam
                                        vel, ullamcorper sit amet ligula. Proin eget tortor risus.</p>
                                        <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem
                                        ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet
                                        elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum
                                        porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus
                                        nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
                                        Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Sed
                                        porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum
                                        sed sit amet dui. Proin eget tortor risus.</p>
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-2" role="tabpanel">
                                <div class="product__details__tab__desc">
                                    <h6>Products Infomation</h6>
                                    <p>Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
                                        Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus.
                                        Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam
                                        sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo
                                        eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.
                                        Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent
                                        sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac
                                        diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante
                                        ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                                        Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
                                        Proin eget tortor risus.</p>
                                    <p>Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem
                                        ipsum dolor sit amet, consectetur adipiscing elit. Mauris blandit aliquet
                                        elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum
                                        porta. Cras ultricies ligula sed magna dictum porta. Sed porttitor lectus
                                        nibh. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.</p>
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-3" role="tabpanel">
                                <div class="product__details__tab__desc">
                                    <h6>Products Infomation</h6>
                                    <p>Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.
                                        Pellentesque in ipsum id orci porta dapibus. Proin eget tortor risus.
                                        Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ac diam
                                        sit amet quam vehicula elementum sed sit amet dui. Donec rutrum congue leo
                                        eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat.
                                        Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Praesent
                                        sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum ac
                                        diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante
                                        ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
                                        Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
                                        Proin eget tortor risus.</p>
                                </div>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </section>

   {% endblock %}

templates/website_templates/shop.html
{% extends "base.html" %}

{% block content %}
{% load static %}

    <!-- Hero Section Begin -->

    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/art-materials-colored-pencils.webp' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shop</h2>
                        <div class="breadcrumb__option">
                            <a href="#">Shop</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    <div class="sidebar">

                        {% include 'website_templates/category.html' %}
                    </div>
                    
                </div>
                <div class="col-lg-9 col-md-7" >
                    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-4 col-md-5">
                                <!-- <div class="filter__sort">
                                    <span>Sort By</span>
                                    

                                    
                                </div> -->
                                <div class="dropdown">
                                    <button class="dropbtn">Filter</button>
                                    <div class="dropdown-content">
                                        <a href = "{% url 'website:shop' filter='latest' %}">Default(latest)</a>
                                        <a href = "{% url 'website:shop' filter='lower' %}">lower price</a>
                                     <a href = "{% url 'website:shop' filter='highter' %}">highter price</a>
                                    <a href = "{% url 'website:shop' filter='discount' %}">highter discount</a>
                                    </div>
                                  </div> 

                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="filter__found">
                                    <h6><span>{{items|length}}</span> Products found</h6>
                                </div>
                            </div>
    
                        </div>
                    </div>
                    <div class="row" >
                        {% for item in items %}
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            {% if user.is_authenticated %}
                            <a href="{% url 'website:single' pid=item.id %}"><div class="product__item">
                                {% if item.off %}
                                <div class="product__discount__item">
                                    <div class="product__discount__item__pic set-bg"
                                        data-setbg="{{item.image.url}}">
                                        <div class="product__discount__percent">{{item.discount}}%</div>
                                </div>
                                </div>
                                <div class="product__discount__item__text">
                                    <h5><a>{{item.title}}</h5></a>
                                    <div class="product__item__price">{{item.final_price}}$ <span>{{item.price}}$</span></div>
                                </div>
                                {% else %}
                                <div class="product__item__pic set-bg" data-setbg="{{item.image.url}}">
                                </div>
                                <div class="product__discount__item__text">
                                    <h5><a href="#">{{item.title}}</a></h5>
                                    <div class="product__item__price">{{item.final_price}}$ </div>
                                </div>
                                
                                {% endif %}
                            </div></a>
                            
                            {% else %}
                            <a href="{% url 'accounts:login' %}"><div class="product__item">
                                {% if item.off %}
                                <div class="product__discount__item">
                                    <div class="product__discount__item__pic set-bg"
                                        data-setbg="{{item.image.url}}">
                                        <div class="product__discount__percent">{{item.discount}}%</div>
                                </div>
                                </div>
                                <div class="product__discount__item__text">
                                    <h5><a href="#">{{item.title}}</a></h5>
                                    <div class="product__item__price">{{item.final_price}}$ <span>{{item.price}}$</span></div>
                                </div>
                                {% else %}
                                <div class="product__item__pic set-bg" data-setbg="{{item.image.url}}">
                                </div>
                                <div class="product__discount__item__text">
                                    <h5><a href="#">{{item.title}}</a></h5>
                                    <div class="product__item__price">{{item.final_price}}$ </div>
                                </div>
                                
                                {% endif %}
                            </div></a>
                            
                            {% endif %}
                               
                            
                        </div>
                        {% endfor %}
                           

                    </div>

                    
                </div>
                {% include 'website_templates/shop-paginator.html' %}
            </div>
            
        </div>
        
    </section>
    
    <!-- Product Section End -->

  {% endblock %}