InternetFinalProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_reset/', include('django.contrib.auth.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('login/',login_view,name="login"),
    path('logout/',logout_view,name="logout"),
    path('signup/',signup_view,name="signup"),
    path('forgot-password/', forgot_password, name='forgot_password'),

    path('reset-password/<str:token>/', reset_password, name='reset_password'),
    
]

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'
urlpatterns = [
    #path('url address', 'view', 'name')

    path('',shop_view,name="shop"),
    path('<str:filter>',shop_view,name='shop'),
    path('single/<int:pid>',shop_single,name="single"),
    path('cart/',cart_view,name='cart'),
    path('update_item/', updateItem, name='update_item'),
    path('checkout/',checkout_view,name='checkout'),
    path('search/',search_view,name='search'),
    path('tag/<str:tag_name>',shop_view,name="tag"),
    # path('about',about_view,name="about"),
    # path('test',test,name="test"),
    # path('newsletter',newsletter_view,name="newsletter"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SAMstationary</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="">
                        <div class="header__top__left">
                            <ul>
                                {% if request.user.is_authenticated %}
                                <li><a href="#"><i class="fa fa-user"></i> Logged in as {{request.user.username}}</a></li>
                                <li><a href="{% url 'accounts:logout' %}" ><i class="fa fa-user"></i>Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login' %}"><i class="fa fa-user"></i>Login</a></li>
                                <li><a href="{% url 'accounts:signup' %}" ><i class="fa fa-user"></i>Sign up</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
            <div id="popup-container" style="display: block; background-color:aqua; ">
                {% for message in messages %}
                    <div class="popup-notification alert alert-{{ message.tags }}" style="color:red">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="#"><img src="{% static 'img/SAM.png' %}" alt="LOGO"></a>
                    </div>
                </div>
  
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                            <li><a href="{% url 'website:cart' %}"><i class="fa fa-shopping-bag"></i> <span>{{cartItems}}</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </header>

    <section class="hero">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    
                        
                </div>
                <div class="col-lg-12">
                    <div class="hero__search">
                        {% include 'website_templates/search.html' %}
                        
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>09101245263</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                    <div class="hero__item set-bg" data-setbg="{% static 'img/hero/S001525875.webp' %}">
                        <div class="hero__text">
                            <!-- <span>FRUIT FRESH</span> -->
                            <h1>Wide</h1>
                            <h2>variety</h2>
                            <h3>of products</h3>
                            <br>
                            <!-- <h2>Vegetable <br />100% Organic</h2> -->
                            <!-- <p>Free Pickup and Delivery Available</p> -->
                            <a href="{% url 'website:shop' %}" class="primary-btn">SHOP NOW</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% block content %}
    {% endblock %}
    <!-- <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="{% static 'img/SAMLighter.png' %}" alt="LOGO"></a>
                        </div>
                        <ul>
                            <li>Address: Rasht Lakan blv</li>
                            <li>Phone: 09101245263</li>
                            <li>Email: SAMStationary2023@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </footer> -->
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>

    <script type="text/javascript">
        var user =  '{{request.user}}';
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
    </script>
    <script>
        function dismissNotification(notification) {
            setTimeout(function() {
                notification.style.display = 'none';
            }, 3000); // 3000 milliseconds (3 seconds) delay
        }
    
        // Get all notification elements and dismiss them after a delay
        var notifications = document.querySelectorAll('.popup-notification');
        notifications.forEach(function(notification) {
            dismissNotification(notification);
        });


        
    </script>
</body>

</html>